name: test

on:
  push:
    paths:
      - '**.json'
  workflow_dispatch:

env:
  LOG_LEVEL: debug

jobs:
  preset:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        file:
          - default.json
          - sveltekit.json
    env:
      RENOVATE_CONFIG_FILE: ${{ matrix.file }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: testing ${{ matrix.file }}
        run: npx --yes --package renovate@latest -- renovate-config-validator --strict
